version: '3.1'

services:
  db:
    image: mongo
    container_name: shorty_db
    restart: always
    volumes:
        - ./db:/data/db
    ports:
        - "27017:27017"
    
  web:
    build: .
    command: "sh -c 'npm start '"
    container_name: shorty_express
    restart: unless-stopped
    ports:
        - "8080:8080"
    volumes:
        - .:/usr/src/app
    depends_on:
        - db